#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DB}
#    username: artiom
#    password: admin
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: false
#    hibernate:
#      ddl-auto: create

security:
  jwt:
    token:
     secret-key: my-secret-key

spring:
  datasource:
#    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/backenddb
    username: artiom
    password: admin
#    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create